# Sample config for Prometheus.

global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.

scrape_configs:

  - job_name: 'locust'

    scrape_interval: 2s
    scrape_timeout: 2s
    static_configs:
      - targets: ['host.docker.internal:9191']

